version: '3'
services:
  client:
    image: dsm-client
    build:
      context: client
      dockerfile: Dockerfile
      target: build
    ports:
      - 3000:3000
    command: node .output/server/index.mjs &
  server:
    image: dsm-server
    build:
      context: server
      dockerfile: Dockerfile
      target: build
    ports:
      - 3001:3001
    command: node dist/src/main &